version: '3'
services:
  web:
    build: .
    image: "my-hiku:dev"
    command: node --inspect=0.0.0.0:9229 server/server.js
    volumes:
      - ./src:/usr/src
    ports:
      - "8080:8080"
      - "9229:9229"